name: grafana-backup

on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  GIT_USER_NAME: github-actions[bot]
  GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com
  GIT_SRC: 'grafana-backup'
  COMMIT_MSG: 'Backup grafana'

jobs:
  backup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: ['dep', 'main']
        include:
          - instance: 'dep'
            branch: 'dep-azure-1'
            url: 'DEP_GRAFANA_URL'
            api_key: 'DEP_GRAFANA_API_KEY'
          - instance: 'main'
            branch: 'main-azure-1'
            url: 'MAIN_GRAFANA_URL'
            api_key: 'MAIN_GRAFANA_API_KEY'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout grafana backup repo
        uses: actions/checkout@v3
        with:
          repository: vchrombie/floodnet-grafana
          token: ${{ secrets.GH_PAT }}
          ref: ${{ matrix.branch }}
          path: ${{ env.GIT_SRC }}
      - name: Export grafana dashboards and alerts
        env:
          GRAFANA_API_KEY: ${{ secrets[matrix.api_key] }}
          GRAFANA_URL: ${{ secrets[matrix.url] }}
        run: |
          ./.github/scripts/grafana-export.py
      - name: Push to github
        working-directory: ${{ env.GIT_SRC }}
        run: |
          git config --global user.name $GIT_USER_NAME
          git config --global user.email $GIT_USER_EMAIL
          git add .
          git diff --staged --quiet || git commit -m "$COMMIT_MSG $(date +'%Y-%m-%d')"
          git push origin ${{ matrix.branch }}
